# alias staging="docker-compose -d docker-compose.yml -f ci-compose.yml"
version: "3.7"

volumenes:
  gradle_user_home:

web:
  image: brandonveloz/spring-demo:development
  build:
    context: .
    #target: development
    ports:
      - ${DEMO_WEB_PORT:-8080}:8080
    volumes:
      - .:/usr/src
      - gradle_user_home:/usr/local/gradle
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCER_URL: jdbc:postgressql://postgres:5432/demo_development
      SPRING_DATASOURCER_USERNAME: postgres
      SPRING_DATASOURCER_PASSWORD: copsis123