version: "3.7"

volumenes:
  postgres_data:

services:
  postgres:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - ${DEMO_PG_PORT:-5432}:5432
    environment:
      POSTGRES_PASSWORD: copsis123