version: "3.7"

volumes:
  postgres_data:

services:
  postgres:
    image: postgres:12-alpine
    volumes:
    #Compartimos los datos de posgres al volumen del sistema, esta ruta viene en la documentación de la imagén
      - postgres_data:/var/lib/posgresql/postgres_data
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - ${DEMO_PG_PORT:-5432}:5432
    environment:
      POSTGRES_PASSWORD: copsis123
