version: "3.7"

volumes:
  gradle_user_home:

services:
  web:
    image: brandonveloz/spring-demo:development
    build:
      context: .
      target: development
    ports:
      - ${DEMO_WEB_PORT:-8080}:8080
    volumes:
      - .:/usr/src
      - gradle_user_home:/usr/local/gradle
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCER_URL: jdbc:postgressql://postgres:5432/demo_development
      SPRING_DATASOURCER_USERNAME: postgres
      SPRING_DATASOURCER_PASSWORD: copsis123
